using System.Text;
using System.Text.Json;
using Ardalis.GuardClauses;
using FluentValidation;
using NexTraceOne.BuildingBlocks.Application.Cqrs;
using NexTraceOne.BuildingBlocks.Core.Results;
using NexTraceOne.Catalog.Application.Portal.ContractPipeline.Shared;

namespace NexTraceOne.Catalog.Application.Portal.ContractPipeline.Features.GenerateContractTests;

/// <summary>Gera testes de contrato a partir de um OpenAPI spec.</summary>
public static class GenerateContractTests
{
    /// <summary>Comando para gerar testes de contrato.</summary>
    public sealed record Command(
        Guid ContractVersionId,
        string ContractJson,
        string ServiceName,
        string TestFramework = "xunit") : ICommand<Response>;

    /// <summary>Validação do comando.</summary>
    public sealed class Validator : AbstractValidator<Command>
    {
        private static readonly string[] SupportedFrameworks = ["xunit", "nunit", "jest", "robot"];

        public Validator()
        {
            RuleFor(x => x.ContractVersionId).NotEmpty();
            RuleFor(x => x.ContractJson).NotEmpty();
            RuleFor(x => x.ServiceName).NotEmpty().MaximumLength(100);
            RuleFor(x => x.TestFramework)
                .Must(f => SupportedFrameworks.Contains(f.ToLowerInvariant()))
                .WithMessage("TestFramework must be one of: xunit, nunit, jest, robot.");
        }
    }

    /// <summary>Handler que gera ficheiros de testes de contrato.</summary>
    public sealed class Handler : ICommandHandler<Command, Response>
    {
        public Task<Result<Response>> Handle(Command request, CancellationToken cancellationToken)
        {
            Guard.Against.Null(request);

            var endpoints = ExtractEndpoints(request.ContractJson);
            var files = request.TestFramework.ToLowerInvariant() switch
            {
                "xunit" => GenerateXUnitTests(request.ServiceName, endpoints),
                "nunit" => GenerateNUnitTests(request.ServiceName, endpoints),
                "jest" => GenerateJestTests(request.ServiceName, endpoints),
                "robot" => GenerateRobotTests(request.ServiceName, endpoints),
                _ => new List<GeneratedFile>()
            };

            return Task.FromResult(Result<Response>.Success(new Response(
                ContractVersionId: request.ContractVersionId,
                TestFramework: request.TestFramework,
                Files: files,
                TestCount: endpoints.Count)));
        }

        private static List<(string Method, string Path)> ExtractEndpoints(string contractJson)
        {
            var result = new List<(string, string)>();
            try
            {
                using var doc = JsonDocument.Parse(contractJson);
                if (doc.RootElement.TryGetProperty("paths", out var paths))
                {
                    foreach (var path in paths.EnumerateObject())
                        foreach (var method in path.Value.EnumerateObject())
                            result.Add((method.Name.ToUpperInvariant(), path.Name));
                }
            }
            catch (JsonException) { }
            return result;
        }

        private static List<GeneratedFile> GenerateXUnitTests(string serviceName, List<(string Method, string Path)> endpoints)
        {
            var sb = new StringBuilder();
            sb.AppendLine("using System.Net;");
            sb.AppendLine("using System.Net.Http;");
            sb.AppendLine("using Xunit;");
            sb.AppendLine();
            sb.AppendLine($"namespace {serviceName}.Tests.Contract;");
            sb.AppendLine();
            sb.AppendLine($"// Generated by NexTraceOne Contract-to-Code Pipeline");
            sb.AppendLine($"public sealed class {serviceName}ContractTests(HttpClient client)");
            sb.AppendLine("{");

            foreach (var (method, path) in endpoints)
            {
                var testName = $"{method}_{path.Replace("/", "_").TrimStart('_')}_ReturnsExpectedStatus";
                sb.AppendLine($"    [Fact]");
                sb.AppendLine($"    public async Task {testName}()");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        var response = await client.{ToCsharpMethod(method)}Async(\"{path}\");");
                sb.AppendLine($"        Assert.True(response.StatusCode < HttpStatusCode.InternalServerError,");
                sb.AppendLine($"            $\"Expected non-5xx but got {{response.StatusCode}} for {method} {path}\");");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return [new GeneratedFile($"Contract/{serviceName}ContractTests.cs", sb.ToString(), "csharp", $"xUnit contract tests for {serviceName}")];
        }

        private static List<GeneratedFile> GenerateNUnitTests(string serviceName, List<(string Method, string Path)> endpoints)
        {
            var sb = new StringBuilder();
            sb.AppendLine("using NUnit.Framework;");
            sb.AppendLine("using System.Net;");
            sb.AppendLine("using System.Net.Http;");
            sb.AppendLine();
            sb.AppendLine($"// Generated by NexTraceOne Contract-to-Code Pipeline");
            sb.AppendLine($"[TestFixture]");
            sb.AppendLine($"public sealed class {serviceName}ContractTests");
            sb.AppendLine("{");
            sb.AppendLine($"    private HttpClient _client = null!;");
            sb.AppendLine();
            sb.AppendLine($"    [SetUp]");
            sb.AppendLine($"    public void Setup() => _client = new HttpClient {{ BaseAddress = new Uri(\"http://localhost:5000\") }};");
            sb.AppendLine();

            foreach (var (method, path) in endpoints)
            {
                sb.AppendLine($"    [Test]");
                sb.AppendLine($"    public async Task {method}_{path.Replace("/", "_").TrimStart('_')}_ReturnsSuccess()");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        var response = await _client.{ToCsharpMethod(method)}Async(\"{path}\");");
                sb.AppendLine($"        Assert.That((int)response.StatusCode, Is.LessThan(500));");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return [new GeneratedFile($"Contract/{serviceName}ContractTests.cs", sb.ToString(), "csharp", $"NUnit contract tests for {serviceName}")];
        }

        private static List<GeneratedFile> GenerateJestTests(string serviceName, List<(string Method, string Path)> endpoints)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"// Generated by NexTraceOne Contract-to-Code Pipeline");
            sb.AppendLine($"const axios = require('axios');");
            sb.AppendLine($"const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';");
            sb.AppendLine();
            sb.AppendLine($"describe('{serviceName} Contract Tests', () => {{");

            foreach (var (method, path) in endpoints)
            {
                sb.AppendLine($"  test('{method} {path} returns non-5xx', async () => {{");
                sb.AppendLine($"    const response = await axios.{{ method: '{method.ToLower()}', url: `${{BASE_URL}}{path}`, validateStatus: () => true }});");
                sb.AppendLine($"    expect(response.status).toBeLessThan(500);");
                sb.AppendLine($"  }});");
                sb.AppendLine();
            }

            sb.AppendLine("});");
            return [new GeneratedFile($"contract/{serviceName.ToLower()}.contract.test.js", sb.ToString(), "javascript", $"Jest contract tests for {serviceName}")];
        }

        private static List<GeneratedFile> GenerateRobotTests(string serviceName, List<(string Method, string Path)> endpoints)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"*** Settings ***");
            sb.AppendLine($"# Generated by NexTraceOne Contract-to-Code Pipeline");
            sb.AppendLine($"Library    RequestsLibrary");
            sb.AppendLine($"Library    Collections");
            sb.AppendLine();
            sb.AppendLine($"*** Variables ***");
            sb.AppendLine($"${{BASE_URL}}    http://localhost:5000");
            sb.AppendLine();
            sb.AppendLine($"*** Test Cases ***");

            foreach (var (method, path) in endpoints)
            {
                sb.AppendLine($"{method} {path} Contract Test");
                sb.AppendLine($"    [Tags]    contract");
                sb.AppendLine($"    Create Session    api    ${{BASE_URL}}");
                sb.AppendLine($"    ${{response}}=    {method.ToTitleCase()} On Session    api    {path}");
                sb.AppendLine($"    Should Be True    ${{response.status_code}} < 500");
                sb.AppendLine();
            }

            return [new GeneratedFile($"{serviceName.ToLower()}_contract.robot", sb.ToString(), "robot", $"Robot Framework contract tests for {serviceName}")];
        }

        private static string ToCsharpMethod(string method) => method switch
        {
            "GET" => "Get",
            "POST" => "Post",
            "PUT" => "Put",
            "DELETE" => "Delete",
            "PATCH" => "Patch",
            _ => "Get"
        };
    }

    /// <summary>Resposta com ficheiros de testes de contrato gerados.</summary>
    public sealed record Response(
        Guid ContractVersionId,
        string TestFramework,
        IReadOnlyList<GeneratedFile> Files,
        int TestCount);
}

internal static class StringHelperExtensions
{
    public static string ToTitleCase(this string s) =>
        string.IsNullOrEmpty(s) ? s : char.ToUpperInvariant(s[0]) + s[1..].ToLowerInvariant();
}
