// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexTraceOne.BuildingBlocks.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexTraceOne.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(BuildingBlocksDbContext))]
partial class BuildingBlocksDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("NexTraceOne.BuildingBlocks.Infrastructure.Outbox.DeadLetterMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("AttemptCount")
                    .HasColumnType("integer");

                b.Property<DateTimeOffset>("ExhaustedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("FailureReason")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)");

                b.Property<string>("LastException")
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)");

                b.Property<string>("MessageType")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTimeOffset?>("ReprocessedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("ExhaustedAt");

                b.HasIndex("Status");

                b.HasIndex("TenantId");

                b.HasIndex("TenantId", "Status");

                b.ToTable("bb_dead_letter_messages");
            });
#pragma warning restore 612, 618
    }
}
