apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextraceone.fullname" . }}-smtp-secrets
  labels:
    {{- include "nextraceone.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.app.smtp.host | default "" | b64enc | quote }}
  username: {{ .Values.app.smtp.username | default "" | b64enc | quote }}
  password: {{ .Values.app.smtp.password | default "" | b64enc | quote }}
