apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextraceone.fullname" . }}-kafka-secrets
  labels:
    {{- include "nextraceone.labels" . | nindent 4 }}
type: Opaque
data:
  bootstrap-servers: {{ .Values.app.kafka.bootstrapServers | default "" | b64enc | quote }}
