using System.Text.Json;

using NexTraceOne.AuditCompliance.Application.Abstractions;

using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace NexTraceOne.AuditCompliance.Infrastructure.Services;

/// <summary>
/// Renderiza relatórios de auditoria no formato PDF usando QuestPDF.
///
/// Utiliza a licença Community do QuestPDF (gratuita para uso geral).
/// O layout segue o padrão enterprise do NexTraceOne com cabeçalho, corpo tabular e rodapé.
///
/// Persona: Auditor, Executive.
/// </summary>
public sealed class PdfReportRenderer : IReportRenderer
{
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = false,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    /// <inheritdoc />
    public Task<RenderedReport> RenderAsync(
        object report,
        string format,
        CancellationToken cancellationToken = default)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var jsonElement = JsonSerializer.SerializeToElement(report, SerializerOptions);
        var timestamp = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss UTC");

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.MarginHorizontal(40);
                page.MarginVertical(30);
                page.DefaultTextStyle(x => x.FontSize(9).FontColor(Colors.Grey.Darken3));

                // ── Header ──
                page.Header().Column(col =>
                {
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Text("NexTraceOne — Audit Report")
                            .Bold().FontSize(16).FontColor(Colors.Blue.Darken2);
                        row.ConstantItem(140).AlignRight().Text(timestamp)
                            .FontSize(8).FontColor(Colors.Grey.Medium);
                    });
                    col.Item().PaddingVertical(4).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                });

                // ── Content ──
                page.Content().PaddingVertical(10).Column(col =>
                {
                    RenderJsonElement(col, jsonElement, depth: 0);
                });

                // ── Footer ──
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                    text.Span("  |  Generated by NexTraceOne Audit Module");
                });
            });
        });

        var bytes = document.GeneratePdf();

        return Task.FromResult(new RenderedReport(
            bytes,
            "application/pdf",
            $"audit-report-{DateTime.UtcNow:yyyyMMdd-HHmmss}.pdf"));
    }

    /// <summary>
    /// Renderiza recursivamente um JsonElement como conteúdo PDF estruturado.
    /// </summary>
    private static void RenderJsonElement(ColumnDescriptor col, JsonElement element, int depth)
    {
        switch (element.ValueKind)
        {
            case JsonValueKind.Object:
                foreach (var property in element.EnumerateObject())
                {
                    if (property.Value.ValueKind is JsonValueKind.Object or JsonValueKind.Array)
                    {
                        col.Item().PaddingTop(depth > 0 ? 6 : 10)
                            .PaddingLeft(depth * 12)
                            .Text(FormatKey(property.Name))
                            .Bold().FontSize(10).FontColor(Colors.Blue.Darken1);

                        RenderJsonElement(col, property.Value, depth + 1);
                    }
                    else
                    {
                        col.Item().PaddingLeft(depth * 12).Row(row =>
                        {
                            row.ConstantItem(180).Text(FormatKey(property.Name))
                                .SemiBold().FontColor(Colors.Grey.Darken2);
                            row.RelativeItem().Text(FormatValue(property.Value))
                                .FontColor(Colors.Grey.Darken3);
                        });
                    }
                }
                break;

            case JsonValueKind.Array:
                var index = 0;
                foreach (var item in element.EnumerateArray())
                {
                    col.Item().PaddingTop(4).PaddingLeft(depth * 12)
                        .Text($"[{index}]")
                        .FontSize(8).FontColor(Colors.Grey.Medium);
                    RenderJsonElement(col, item, depth + 1);
                    index++;
                }
                break;

            default:
                col.Item().PaddingLeft(depth * 12)
                    .Text(FormatValue(element));
                break;
        }
    }

    private static string FormatKey(string key)
    {
        // camelCase → Title Case
        if (string.IsNullOrEmpty(key)) return key;
        var result = new System.Text.StringBuilder();
        result.Append(char.ToUpper(key[0], System.Globalization.CultureInfo.InvariantCulture));
        for (var i = 1; i < key.Length; i++)
        {
            if (char.IsUpper(key[i]) && !char.IsUpper(key[i - 1]))
                result.Append(' ');
            result.Append(key[i]);
        }
        return result.ToString();
    }

    private static string FormatValue(JsonElement el) => el.ValueKind switch
    {
        JsonValueKind.String => el.GetString() ?? "",
        JsonValueKind.Number => el.GetRawText(),
        JsonValueKind.True => "Yes",
        JsonValueKind.False => "No",
        JsonValueKind.Null => "—",
        _ => el.GetRawText()
    };
}
