using FluentValidation;

using NexTraceOne.BuildingBlocks.Application.Abstractions;
using NexTraceOne.BuildingBlocks.Application.Cqrs;
using NexTraceOne.BuildingBlocks.Core.Results;

namespace NexTraceOne.IdentityAccess.Application.Features.ResendMfaCode;

/// <summary>
/// Feature: ResendMfaCode — reenvia o código MFA ao utilizador.
/// Stub controlado: MFA usa TOTP (Time-based OTP), portanto não há reenvio de código.
/// Retorna erro explicativo para que o frontend possa orientar o utilizador.
/// </summary>
public static class ResendMfaCode
{
    public sealed record Command(string SessionId) : ICommand<Response>, IPublicRequest;

    public sealed class Validator : AbstractValidator<Command>
    {
        public Validator()
        {
            RuleFor(x => x.SessionId).NotEmpty().MaximumLength(512);
        }
    }

    public sealed record Response(bool Sent);

    internal sealed class Handler : ICommandHandler<Command, Response>
    {
        public Task<Result<Response>> Handle(Command request, CancellationToken cancellationToken)
        {
            // MFA usa TOTP — o código é gerado pelo authenticator do utilizador.
            // Reenvio de código requer integração com canal de entrega (SMS/email).
            return Task.FromResult<Result<Response>>(
                Error.Business("mfa.resend.not_supported",
                    "MFA uses TOTP — code is generated by your authenticator app"));
        }
    }
}
