using System.Text;
using Ardalis.GuardClauses;
using FluentValidation;
using NexTraceOne.BuildingBlocks.Application.Cqrs;
using NexTraceOne.BuildingBlocks.Core.Results;
using NexTraceOne.Catalog.Application.Portal.ContractPipeline.Shared;

namespace NexTraceOne.Catalog.Application.Portal.ContractPipeline.Features.GenerateClientSdkFromContract;

/// <summary>Gera SDK cliente tipado a partir de um contrato OpenAPI.</summary>
public static class GenerateClientSdkFromContract
{
    /// <summary>Comando para gerar SDK cliente.</summary>
    public sealed record Command(
        Guid ContractVersionId,
        string TargetLanguage,
        string ClientName) : ICommand<Response>;

    /// <summary>Validação do comando.</summary>
    public sealed class Validator : AbstractValidator<Command>
    {
        private static readonly string[] SupportedLanguages = ["dotnet", "typescript", "java", "python"];

        public Validator()
        {
            RuleFor(x => x.ContractVersionId).NotEmpty();
            RuleFor(x => x.ClientName).NotEmpty().MaximumLength(100);
            RuleFor(x => x.TargetLanguage)
                .Must(l => SupportedLanguages.Contains(l.ToLowerInvariant()))
                .WithMessage("TargetLanguage must be one of: dotnet, typescript, java, python.");
        }
    }

    /// <summary>Handler que gera o SDK cliente.</summary>
    public sealed class Handler : ICommandHandler<Command, Response>
    {
        public Task<Result<Response>> Handle(Command request, CancellationToken cancellationToken)
        {
            Guard.Against.Null(request);

            var files = request.TargetLanguage.ToLowerInvariant() switch
            {
                "dotnet" => GenerateDotNetClient(request.ClientName),
                "typescript" => GenerateTypeScriptClient(request.ClientName),
                "java" => GenerateJavaClient(request.ClientName),
                "python" => GeneratePythonClient(request.ClientName),
                _ => new List<GeneratedFile>()
            };

            return Task.FromResult(Result<Response>.Success(new Response(
                ContractVersionId: request.ContractVersionId,
                TargetLanguage: request.TargetLanguage,
                ClientName: request.ClientName,
                Files: files)));
        }

        private static List<GeneratedFile> GenerateDotNetClient(string clientName)
        {
            return
            [
                new GeneratedFile(
                    $"{clientName}.cs",
                    $$"""
                    using System.Net.Http;
                    using System.Text;
                    using System.Text.Json;
                    using System.Threading;
                    using System.Threading.Tasks;

                    // Generated by NexTraceOne Contract-to-Code Pipeline
                    namespace Clients;

                    public sealed class {{clientName}}(HttpClient httpClient)
                    {
                        private static readonly JsonSerializerOptions s_options = new() { PropertyNameCaseInsensitive = true };

                        public async Task<HttpResponseMessage> GetAllAsync(CancellationToken ct = default)
                            => await httpClient.GetAsync("/api/v1/resource", ct);

                        public async Task<HttpResponseMessage> GetByIdAsync(Guid id, CancellationToken ct = default)
                            => await httpClient.GetAsync($"/api/v1/resource/{id}", ct);

                        public async Task<HttpResponseMessage> CreateAsync<TRequest>(TRequest request, CancellationToken ct = default)
                        {
                            var json = JsonSerializer.Serialize(request, s_options);
                            return await httpClient.PostAsync("/api/v1/resource", new StringContent(json, Encoding.UTF8, "application/json"), ct);
                        }

                        public async Task<HttpResponseMessage> DeleteAsync(Guid id, CancellationToken ct = default)
                            => await httpClient.DeleteAsync($"/api/v1/resource/{id}", ct);
                    }
                    """,
                    "csharp",
                    $"C# HTTP client for {clientName}")
            ];
        }

        private static List<GeneratedFile> GenerateTypeScriptClient(string clientName)
        {
            return
            [
                new GeneratedFile(
                    $"{clientName}.ts",
                    $$"""
                    // Generated by NexTraceOne Contract-to-Code Pipeline

                    export class {{clientName}} {
                        constructor(private readonly baseUrl: string, private readonly headers: Record<string, string> = {}) {}

                        async getAll(): Promise<Response> {
                            return fetch(`${this.baseUrl}/api/v1/resource`, { headers: this.headers });
                        }

                        async getById(id: string): Promise<Response> {
                            return fetch(`${this.baseUrl}/api/v1/resource/${id}`, { headers: this.headers });
                        }

                        async create<T>(body: T): Promise<Response> {
                            return fetch(`${this.baseUrl}/api/v1/resource`, {
                                method: 'POST',
                                headers: { ...this.headers, 'Content-Type': 'application/json' },
                                body: JSON.stringify(body)
                            });
                        }

                        async delete(id: string): Promise<Response> {
                            return fetch(`${this.baseUrl}/api/v1/resource/${id}`, {
                                method: 'DELETE',
                                headers: this.headers
                            });
                        }
                    }
                    """,
                    "typescript",
                    $"TypeScript HTTP client for {clientName}")
            ];
        }

        private static List<GeneratedFile> GenerateJavaClient(string clientName)
        {
            return
            [
                new GeneratedFile(
                    $"{clientName}.java",
                    $$"""
                    import java.net.URI;
                    import java.net.http.HttpClient;
                    import java.net.http.HttpRequest;
                    import java.net.http.HttpResponse;
                    import java.util.UUID;

                    // Generated by NexTraceOne Contract-to-Code Pipeline
                    public class {{clientName}} {
                        private final HttpClient client = HttpClient.newHttpClient();
                        private final String baseUrl;

                        public {{clientName}}(String baseUrl) { this.baseUrl = baseUrl; }

                        public HttpResponse<String> getAll() throws Exception {
                            return client.send(HttpRequest.newBuilder().GET().uri(URI.create(baseUrl + "/api/v1/resource")).build(), HttpResponse.BodyHandlers.ofString());
                        }

                        public HttpResponse<String> getById(UUID id) throws Exception {
                            return client.send(HttpRequest.newBuilder().GET().uri(URI.create(baseUrl + "/api/v1/resource/" + id)).build(), HttpResponse.BodyHandlers.ofString());
                        }
                    }
                    """,
                    "java",
                    $"Java HTTP client for {clientName}")
            ];
        }

        private static List<GeneratedFile> GeneratePythonClient(string clientName)
        {
            var lowerName = clientName.ToLower();
            return
            [
                new GeneratedFile(
                    $"{lowerName}.py",
                    $$"""
                    import httpx

                    # Generated by NexTraceOne Contract-to-Code Pipeline
                    class {{clientName}}:
                        def __init__(self, base_url: str, headers: dict = None):
                            self.base_url = base_url
                            self.client = httpx.Client(headers=headers or {})

                        def get_all(self):
                            return self.client.get(f"{self.base_url}/api/v1/resource")

                        def get_by_id(self, id: str):
                            return self.client.get(f"{self.base_url}/api/v1/resource/{id}")

                        def create(self, body: dict):
                            return self.client.post(f"{self.base_url}/api/v1/resource", json=body)

                        def delete(self, id: str):
                            return self.client.delete(f"{self.base_url}/api/v1/resource/{id}")
                    """,
                    "python",
                    $"Python HTTP client for {clientName}")
            ];
        }
    }

    /// <summary>Resposta com ficheiros do SDK cliente gerado.</summary>
    public sealed record Response(
        Guid ContractVersionId,
        string TargetLanguage,
        string ClientName,
        IReadOnlyList<GeneratedFile> Files);
}
