// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexTraceOne.OperationalIntelligence.Infrastructure.TelemetryStore.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexTraceOne.OperationalIntelligence.Infrastructure.TelemetryStore.Persistence.Migrations
{
    [DbContext(typeof(TelemetryStoreDbContext))]
    [Migration("20260511135619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexTraceOne.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ProcessedAt");

                    b.ToTable("ops_telstore_outbox_messages", (string)null);
                });

            modelBuilder.Entity("NexTraceOne.BuildingBlocks.Observability.Telemetry.Models.AnomalySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnomalyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CorrelatedReleaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DeviationPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("ExpectedValue")
                        .HasColumnType("double precision");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("ObservedValue")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Severity", "ResolvedAt");

                    b.HasIndex("ServiceId", "Environment", "DetectedAt");

                    b.ToTable("ops_ts_anomaly_snapshots", (string)null);
                });

            modelBuilder.Entity("NexTraceOne.BuildingBlocks.Observability.Telemetry.Models.DependencyMetricsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AggregationLevel")
                        .HasColumnType("integer");

                    b.Property<long>("CallCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint");

                    b.Property<double>("ErrorRatePercent")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("IntervalEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IntervalStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LatencyAvgMs")
                        .HasColumnType("double precision");

                    b.Property<double>("LatencyP95Ms")
                        .HasColumnType("double precision");

                    b.Property<double>("LatencyP99Ms")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SourceServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TargetServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceServiceId", "TargetServiceId", "Environment", "AggregationLevel", "IntervalStart");

                    b.ToTable("ops_ts_dependency_metrics", (string)null);
                });

            modelBuilder.Entity("NexTraceOne.BuildingBlocks.Observability.Telemetry.Models.InvestigationContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedServiceIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AiSummaryJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("AnomalySnapshotIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InvestigationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PrimaryServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReleaseCorrelationIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelemetryReferenceIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TimeWindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TimeWindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TitleMessageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("PrimaryServiceId", "Environment", "Status");

                    b.ToTable("ops_ts_investigation_contexts", (string)null);
                });

            modelBuilder.Entity("NexTraceOne.BuildingBlocks.Observability.Telemetry.Models.ObservedTopologyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommunicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsShadowDependency")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TargetServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalCallCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Environment", "IsShadowDependency");

                    b.HasIndex("SourceServiceId", "TargetServiceId", "Environment", "CommunicationType")
                        .IsUnique();

                    b.ToTable("ops_ts_observed_topology", (string)null);
                });

            modelBuilder.Entity("NexTraceOne.BuildingBlocks.Observability.Telemetry.Models.ReleaseRuntimeCorrelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImpactClassification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("ImpactScore")
                        .HasColumnType("double precision");

                    b.Property<string>("MarkerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("PostDeployErrorRate")
                        .HasColumnType("double precision");

                    b.Property<double>("PostDeployLatencyP95Ms")
                        .HasColumnType("double precision");

                    b.Property<double>("PostDeployRequestsPerMinute")
                        .HasColumnType("double precision");

                    b.Property<double>("PreDeployErrorRate")
                        .HasColumnType("double precision");

                    b.Property<double>("PreDeployLatencyP95Ms")
                        .HasColumnType("double precision");

                    b.Property<double>("PreDeployRequestsPerMinute")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TelemetryReferenceIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("ServiceId", "Environment", "DeployedAt");

                    b.ToTable("ops_ts_release_correlations", (string)null);
                });

            modelBuilder.Entity("NexTraceOne.BuildingBlocks.Observability.Telemetry.Models.ServiceMetricsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AggregationLevel")
                        .HasColumnType("integer");

                    b.Property<double?>("CpuAvgPercent")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint");

                    b.Property<double>("ErrorRatePercent")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("IntervalEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IntervalStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LatencyAvgMs")
                        .HasColumnType("double precision");

                    b.Property<double>("LatencyMaxMs")
                        .HasColumnType("double precision");

                    b.Property<double>("LatencyP50Ms")
                        .HasColumnType("double precision");

                    b.Property<double>("LatencyP95Ms")
                        .HasColumnType("double precision");

                    b.Property<double>("LatencyP99Ms")
                        .HasColumnType("double precision");

                    b.Property<double?>("MemoryAvgMb")
                        .HasColumnType("double precision");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint");

                    b.Property<double>("RequestsPerHour")
                        .HasColumnType("double precision");

                    b.Property<double>("RequestsPerMinute")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceName", "Environment", "IntervalStart");

                    b.HasIndex("ServiceId", "Environment", "AggregationLevel", "IntervalStart");

                    b.ToTable("ops_ts_service_metrics", (string)null);
                });

            modelBuilder.Entity("NexTraceOne.BuildingBlocks.Observability.Telemetry.Models.TelemetryReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessUri")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("BackendType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("OriginalTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SignalType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ServiceId", "SignalType", "OriginalTimestamp");

                    b.ToTable("ops_ts_telemetry_references", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
