// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexTraceOne.Catalog.Infrastructure.Contracts.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexTraceOne.Catalog.Infrastructure.Contracts.Persistence.Migrations
{
    [DbContext(typeof(ContractsDbContext))]
    [Migration("20260522130000_AddCodeQualityRecords")]
    partial class AddCodeQualityRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Regenerate with: dotnet ef migrations add <next> --context ContractsDbContext
            // to get the full auto-generated snapshot here.
        }
    }
}
